- name: Get ansible facts
  hosts: device_roles_db-tier
  tasks:
    - name: Display all variables/facts known for a host
      debug:
        msg: "{{ hostvars['mysql-100']['ansible_facts'][ansible_all_ipv4_addresses[0]] }}"

# - name: LINUX High Availability and CLUSTER Setup
#   hosts: device_roles_web-tier
#   ignore_errors: true
#   ignore_unreachable: true
#   roles:
#     - ha-cluster-setup
#   become: yes