- name: Get ansible facts
  hosts: device_roles_db-tier

# - name: Display all variables/facts known for a host
#   debug:
#     var: "{{ hostvars[ansible_host] }}"
#     verbosity: 4

# - name: LINUX High Availability and CLUSTER Setup
#   hosts: device_roles_web-tier
#   ignore_errors: true
#   ignore_unreachable: true
#   roles:
#     - ha-cluster-setup
#   become: yes